version: '3'

vars:
  NOTIFY_TITLE: System Maintenance
  INSTALLER: uv run --directory $HOME/projects/archinstall-midgard installer

tasks:
  default:
    desc: run system update
    cmds:
      - sudo pacman -Syu
      - yay -Syu --aur --answerclean None --answerdiff None --noconfirm --needed
      - notify-send -t 5000 "{{.NOTIFY_TITLE}}" "Update complete"
    silent: true
  daily:
    desc: run daily maintenance
    cmds:
      - "{{.INSTALLER}} daily"
      - "{{.INSTALLER}} cleanup"
      - notify-send -t 5000 "{{.NOTIFY_TITLE}}" "Daily maintenance complete"
    silent: true
  clean:
    desc: run package clean up
    cmds:
      - sudo paccache -ruk0
      - sudo paccache -rk1
      - "{{.INSTALLER}} cleanup"
      - notify-send -t 5000 "{{.NOTIFY_TITLE}}" "Package clean-up complete"
    silent: true
  check:
    desc: check for pacnew/pacsave files in /etc
    cmds:
      - sudo find /etc -name '*.pacnew' -o -name '*.pacsave'
      - notify-send -t 5000 "{{.NOTIFY_TITLE}}" "Check for .pacsave, .pacnew complete"
    silent: true
