version: '3'

tasks:
  default:
    desc: run system update
    cmds:
      - sudo pacman -Syu
      - notify-send -t 5000 "update complete"
    silent: true
  daily:
    desc: run daily maintenance script
    cmds:
      - $HOME/projects/archinstall-midgard/scripts/daily.sh
      - $HOME/projects/archinstall-midgard/scripts/cleanup_packages.sh
      - notify-send -t 5000 "daily maintenance complete"
    silent: true
  clean:
    desc: run clean up scripts
    cmds:
      - sudo paccache -ruk0
      - sudo paccache -rk1
      - $HOME/projects/archinstall-midgard/scripts/cleanup_packages.sh
      - notify-send -t 5000 "clean-up complete"
    silent: true
  check:
    desc: check for pacnew/pacsave files in /etc
    cmds:
      - sudo find /etc -name '*.pacnew' -o -name '*.pacsave'
    silent: true
