name: validate

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            scripts:
              - "scripts/**/*.sh"

      - name: run shellcheck
        if: steps.changes.outputs.scripts == 'true'
        run: shellcheck -x scripts/*.sh
